#!/usr/bin/env bash

LOG_PATH="/tmp/podman-service.log"
TIME_TO_SLEEP="0.2"
LOCKFILE="/tmp/podman.lock"

podman_rootless() {
  SOCKET_PATH="/run/user/$(id -u)/podman/podman.sock"

  if [[ -f "$LOCKFILE" ]]; then
    echo "⚠️ Podman daemon seems to be starting already (lockfile exists: $LOCKFILE)"
    exit 1
  fi

  touch "$LOCKFILE"
  trap 'rm -f "$LOCKFILE"' EXIT

  echo "🚀 Starting Podman Daemon in rootless mode..."

  nohup podman system service unix://$SOCKET_PATH --time=0 >"$LOG_PATH" 2>&1 &

  for i in $(seq 1 50); do
    if [[ -S "$SOCKET_PATH" ]]; then
      echo "✅ Podman started successfully in background"
      exit 0
    fi
    sleep "$TIME_TO_SLEEP"
  done

  echo "❎ Failed to start Podman daemon. See $LOG_PATH for details"
  exit 1
}

podman_rootless
